# config/competitors.yaml
# Starter list: LV/Baltics tiles categories. Selectors are common defaults and may need 1–2 tweaks via DevTools.
sites:
  - name: "220.lv — Grīdas flīzes"
    base_url: "https://220.lv/lv/gridas-segumi/gridas-flizes"
    type: "list"
    selectors:
      item: ".product-card, .product-item, li.product"
      title: ".product-title, .product-name, a[title]"
      price: ".product-price, .price, .current-price, .price__main"
      link: "a.product-link, a[href*='/lv/'], a[href*='/p/']"
      availability: ".availability, .stock, .status"
  - name: "220.lv — Sienas flīzes"
    base_url: "https://220.lv/lv/majai-un-remontam/sienu-apdare/sienas-flizes"
    type: "list"
    selectors:
      item: ".product-card, .product-item, li.product"
      title: ".product-title, .product-name, a[title]"
      price: ".product-price, .price, .current-price, .price__main"
      link: "a.product-link, a[href*='/lv/'], a[href*='/p/']"
      availability: ".availability, .stock, .status"
  - name: "Kurši — Grīdas flīzes"
    base_url: "https://www.kursi.lv/lv/apdares-materiali/flizes-flizesanas-materiali/gridas-flizes/"
    type: "list"
    selectors:
      item: ".product, .product-item, .products-grid > *"
      title: ".product-title a, .product__name a, a.product-item-link"
      price: ".price, .price-wrapper, .special-price"
      link: "a.product-item-link, .product-title a, a[href*='/lv/']"
      availability: ".stock, .availability, .product-stock"
  - name: "Kurši — Sienas flīzes"
    base_url: "https://www.kursi.lv/lv/apdares-materiali/flizes-flizesanas-materiali/sienas-flizes/"
    type: "list"
    selectors:
      item: ".product, .product-item, .products-grid > *"
      title: ".product-title a, .product__name a, a.product-item-link"
      price: ".price, .price-wrapper, .special-price"
      link: "a.product-item-link, .product-title a, a[href*='/lv/']"
      availability: ".stock, .availability, .product-stock"
  - name: "K SENUKAI — Flīzes"
    base_url: "https://www.ksenukai.lv/c/apdares-materiali/flizes/1gl"
    type: "list"
    selectors:
      item: ".product, .product-card, .catalog-taxons-product"
      title: ".catalog-taxons-product__name a, .product-title a, a.product__name"
      price: ".price, .product__price, .catalog-taxons-product__price-current"
      link: ".catalog-taxons-product__name a, a[href*='/p/'], a[href*='/c/']"
      availability: ".stock, .availability, .product__availability"
  - name: "DEPO — Flīzes"
    base_url: "https://online.depo.lv/products/5843"
    type: "list"
    selectors:
      item: ".product, .product-card, .product-list__item"
      title: ".product__title a, .product-title a, a.product__name"
      price: ".price, .product__price, .product-price"
      link: ".product__title a, a[href*='/product/'], a[href*='/products/']"
      availability: ".stock, .availability, .product__availability"
